# Generated by Django 4.2.4 on 2023-11-26 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('registered', 'Зарегистрировано'), ('made', 'Сформировано'), ('approved', 'Принято'), ('denied', 'Отказано'), ('deleted', 'Отменено')], max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('editing_date', models.DateTimeField(blank=True, null=True)),
                ('approving_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsesVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'responses_vacancies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.IntegerField()),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('exp', models.CharField(blank=True, max_length=255)),
                ('image', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, size=None)),
                ('conditions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, size=None)),
                ('status', models.CharField(choices=[('enabled', 'enabled'), ('deleted', 'deleted')], default='enabled', max_length=255)),
            ],
            options={
                'db_table': 'vacancies',
                'managed': False,
            },
        ),
    ]
